In [13]:
%tensorflow_version 2.x

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [18]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [19]:
#Create a TensorFlow Constant

my_constant = tf.constant([1, 2, 3])

print(my_constant)


tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [20]:
#Perform Element-Wise Operation

a = tf.constant([2, 4, 6])
b = tf.constant([1, 2, 3])
c = tf.multiply(a, b)

print(c)


tf.Tensor([ 2  8 18], shape=(3,), dtype=int32)


In [21]:
#Reshape a Tensor

x = tf.constant([1, 2, 3, 4, 5, 6])
x_reshaped = tf.reshape(x, shape=(2, 3))

print(x_reshaped)


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [22]:
#Extract a Slice: extract the middle column using TensorFlow.

matrix = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
middle_column = matrix[:, 1]

print(middle_column)

tf.Tensor([2 5 8], shape=(3,), dtype=int32)


In [23]:
#Variable Initialization:a 3x3 matrix of random values.

weights = tf.Variable(tf.random.normal([3, 3]))

print(weights)


<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[-0.24441454,  0.52274066, -0.25477964],
       [-0.41695136, -0.2614114 , -0.19069499],
       [ 0.8897258 ,  0.14569704,  0.29419377]], dtype=float32)>


In [31]:
#Math Operations
y = tf.constant([4.0, 9.0, 16.0])
square_root = tf.sqrt(y)

print(square_root)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)
